"""
SAS Program Generator - Generates SAS programs from analysis specifications.
Produces SAS programs that match the format of .knowledge/TLF/Pgm/ files.
"""

from typing import Dict, List, Any, Optional
from pathlib import Path
from datetime import datetime


# SAS Macro to Analysis Type Mapping
STAT_TYPE_TO_MACRO = {
    "flag_count": {"macro": "Discrete_simple", "result_style": "n"},
    "freq_with_pct": {"macro": "Discrete_simple", "result_style": "freq_format"},
    "continuous": {"macro": "Descriptive_Basic", "result_style": "n mean sd median min_max"},
    "ae_nested": {"macro": "Discrete_nested", "result_style": "freq_format"},
    "survival": {"macro": "lifetest", "result_style": "survival"},
}


class SASProgramGenerator:
    """Generates SAS TLF programs from analysis specifications."""

    # Header template matching reference TLF programs exactly
    HEADER_TEMPLATE = """/*--------------------------------------------------------------------------------------------*
Company Name:         Generated by AI Agent
Protocol ID:
Program:              Table {table_id}.sas
Purpose:              Generate {table_name}
Input Files:          ADaM.{dataset_upper}
Output Files:         RTF
Macro:
Author:               AI Agent
Date Generated:       {timestamp}
*--------------------------------------------------------------------------------------------**/

%include '_setup.sas';

%let Columns = %str(rowlabel _col_1 _col_2 _col_3 _col_99999);

%let tableid = %str(Table {table_id});

%let tablename = %str({table_name});

%let tablepop = %str({analysis_set});

%let datasource = %str(ADaM.{dataset_upper});

%let column = %str({group_by});

%let denom = %str({dataset_upper});

%let denomvar = %str(&column);

%let total = %str(Y);

%let g_distinct = %str(USUBJID);

%let byvar_format = %str( );

%let MaxPageLines = %str(21);

%let BreakIndexGroup = %str(N);

%let reflisting = %str(Listing 16.2.1.1);

%let column_definition = %str(
rowlabel label="" width=2.5 headerjust=l columnjust=l
_col_1 label="{col1_label}`(N=&n_1)" width=1 headerjust=c columnjust=c
_col_2 label="{col2_label}`(N=&n_2)" width=1 headerjust=c columnjust=c
_col_3 label="{col3_label}`(N=&n_3)" width=1 headerjust=c columnjust=c
_col_99999 label="Total`(N=&n_99999)" width=1 headerjust=c columnjust=c
);

%import;

{data_prep}
"""

    DATA_PREP_DISPOSITION = """
data enrlpop;
  set adsl;
  where enrlfl='Y';
 run;

 data safpop;
   set adsl;
   where saffl='Y';
  run;
"""

    DATA_PREP_DEFAULT = """
data enrlpop;
  set adsl;
  where enrlfl='Y';
 run;

 data safpop;
   set adsl;
   where saffl='Y';
  run;
"""

    DATA_PREP_CUSTOM = """
{data}
"""

    # Discrete_simple analysis unit template
    DISCRETE_SIMPLE_UNIT = """
/*{comment}*/
%Discrete_simple(
inds = &inds
,filter = {filter}
,byvars = {byvars}
,column = &column
,avar = {avar}
,grouptitle = {grouptitle}
,grouptitle1 = {grouptitle1}
,total = &total
,result_style = {result_style}
,denom = {denom}
,denomvar = &denomvar
,avar_displayformat = {avar_displayformat}
,byvars_displayformat = {byvars_displayformat}
,level = {level}
,distinct = &g_distinct
,group_position = TOP
,newindex = {newindex}
,weightvar = {weightvar}
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = {outfilter}
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = {groupstyle}
,CalculateCI = N
,keepdenom = Y
,distinct_event = {distinct_event}
,byformat_jointype = full
,sortByCol = {sortBycol}
,avarselcrit = {avarselcrit}
,total_style = {total_style}
,totalfilter = {totalfilter}
,index = {index}
,CalculateP = {CalculateP}
,compspace = Y
,alpha = 0.05
, outds = {outds}
);
"""

    # Descriptive_Basic analysis unit template
    DESCRIPTIVE_BASIC_UNIT = """
/*{comment}*/
%Descriptive_Basic(
inds = &inds
,filter = {filter}
,column = &column
,byvars = {byvars}
,grouptitle = {grouptitle}
,avar = {avar}
,chgvar = {chgvar}
,pchgvar = {pchgvar}
,basevar = {basevar}
,total = &total
,result_style = {result_style}
,denom = {denom}
,denomvar = &denomvar
,avar_displayformat = {avar_displayformat}
,byvars_displayformat = {byvars_displayformat}
,level = {level}
,distinct = &g_distinct
,group_position = TOP
,newindex = {newindex}
,FillBlankColumn = Y
,DelBlankRow = N
,outfilter = {outfilter}
,layout = VV
,geoinds = {geoinds}
,alpha = 0.05
,autoformat = &autoformat
,autoformatby = {autoformatby}
,decimalplace = {decimalplace}
,basedecimalplace = {basedecimalplace}
,compspace = Y
,groupstyle = {groupstyle}
,FillBlankStyle = &misschar
,round = {round}
,byformat_jointype = full
,chgfilter = col1^=.
,pchgdecimal = 1
,calculateCI = N
,index = {index}
,totalfilter = {totalfilter}
, outds = {outds}
);
"""

    # Footer template
    FOOTER_TEMPLATE = """
%output;%delvars;

run;
"""

    def __init__(self):
        self.timestamp = datetime.now().strftime("%Y-%m-%d")

    def generate_program(
        self,
        table_id: str,
        table_name: str,
        analysis_set: str,
        group_by: str,
        dataset: str,
        treatment_labels: Dict[int, str] = None,
        analysis_units: List[Dict] = None,
        data_prep_code: str = None
    ) -> str:
        """
        Generate a complete SAS TLF program.

        Args:
            table_id: Table identifier (e.g., "14.1.1.1")
            table_name: Table name
            analysis_set: Analysis set name
            group_by: Grouping variable (usually treatment)
            dataset: ADaM dataset name
            treatment_labels: Dict mapping treatment number to label (e.g., {1: "Treatment A", ...})
            analysis_units: List of analysis unit specifications
            data_prep_code: Custom data preparation code

        Returns:
            Generated SAS program code
        """
        if treatment_labels is None:
            treatment_labels = {1: "Treatment A", 2: "Treatment B", 3: "Treatment C"}

        # Build header
        header = self.HEADER_TEMPLATE.format(
            table_id=table_id,
            table_name=table_name,
            analysis_set=analysis_set,
            group_by=group_by,
            dataset_upper=dataset.upper(),
            timestamp=self.timestamp,
            col1_label=treatment_labels.get(1, "Treatment 1"),
            col2_label=treatment_labels.get(2, "Treatment 2"),
            col3_label=treatment_labels.get(3, "Treatment 3"),
            data_prep=data_prep_code or self.DATA_PREP_DEFAULT
        )

        # Build analysis units
        units_code = ""
        if analysis_units:
            for i, unit in enumerate(analysis_units):
                units_code += self._generate_unit_code(unit, i + 1)

        # Build footer
        footer = self.FOOTER_TEMPLATE

        return header + units_code + footer

    def _generate_unit_code(self, unit: Dict, index: int) -> str:
        """Generate SAS code for a single analysis unit."""
        macro_type = unit.get("type", "Discrete_simple")

        if macro_type == "Discrete_simple":
            return self.DISCRETE_SIMPLE_UNIT.format(
                comment=unit.get("comment", ""),
                filter=unit.get("filter", ""),
                byvars=unit.get("byvars", ""),
                avar=unit.get("avar", ""),
                grouptitle=unit.get("grouptitle", ""),
                grouptitle1=unit.get("grouptitle1", ""),
                result_style=unit.get("result_style", "freq_format"),
                denom=unit.get("denom", "&denom"),
                avar_displayformat=unit.get("avar_displayformat", ""),
                byvars_displayformat=unit.get("byvars_displayformat", ""),
                level=unit.get("level", 1),
                newindex=unit.get("newindex", "Y"),
                weightvar=unit.get("weightvar", ""),
                outfilter=unit.get("outfilter", ""),
                groupstyle=unit.get("groupstyle", ""),
                distinct_event=unit.get("distinct_event", ""),
                sortBycol=unit.get("sortBycol", ""),
                avarselcrit=unit.get("avarselcrit", ""),
                total_style=unit.get("total_style", ""),
                totalfilter=unit.get("totalfilter", ""),
                index=unit.get("index", ""),
                CalculateP=unit.get("CalculateP", ""),
                outds=unit.get("outds", f"unit{index:02d}")
            )
        elif macro_type == "Descriptive_Basic":
            return self.DESCRIPTIVE_BASIC_UNIT.format(
                comment=unit.get("comment", ""),
                filter=unit.get("filter", ""),
                byvars=unit.get("byvars", ""),
                grouptitle=unit.get("grouptitle", ""),
                avar=unit.get("avar", ""),
                chgvar=unit.get("chgvar", ""),
                pchgvar=unit.get("pchgvar", ""),
                basevar=unit.get("basevar", ""),
                result_style=unit.get("result_style", "n mean sd median min_max"),
                denom=unit.get("denom", "&denom"),
                avar_displayformat=unit.get("avar_displayformat", ""),
                byvars_displayformat=unit.get("byvars_displayformat", ""),
                level=unit.get("level", 1),
                newindex=unit.get("newindex", "Y"),
                outfilter=unit.get("outfilter", ""),
                geoinds=unit.get("geoinds", ""),
                autoformatby=unit.get("autoformatby", ""),
                decimalplace=unit.get("decimalplace", ""),
                basedecimalplace=unit.get("basedecimalplace", ""),
                round=unit.get("round", ""),
                groupstyle=unit.get("groupstyle", ""),
                index=unit.get("index", ""),
                totalfilter=unit.get("totalfilter", ""),
                outds=unit.get("outds", f"unit{index:02d}")
            )
        return ""

    def generate_disposition_program(
        self,
        table_id: str = "14.1.1.1",
        treatment_labels: Dict[int, str] = None
    ) -> str:
        """Generate SAS program for Table 14.1.1.1 (Subject Disposition)."""
        if treatment_labels is None:
            treatment_labels = {1: "Treatment A", 2: "Treatment B", 3: "Treatment C"}

        analysis_units = [
            {
                "type": "Discrete_simple",
                "comment": "Screened",
                "filter": "SCRNFL='Y'",
                "byvars": "",
                "avar": "",
                "grouptitle": "No. of Subjects Screened",
                "grouptitle1": "ongoing",
                "result_style": "n",
                "denom": "&denom",
                "level": 1,
                "newindex": "Y",
                "outds": "unit01"
            },
            {
                "type": "Discrete_simple",
                "comment": "Screen failed",
                "filter": "SCNEFL='Y'",
                "byvars": "",
                "avar": "",
                "grouptitle": "No. of Subjects Screen Failed",
                "grouptitle1": "",
                "result_style": "n",
                "denom": "&denom",
                "level": 1,
                "newindex": "N",
                "outds": "unit02"
            },
            {
                "type": "Discrete_simple",
                "comment": "Enrolled/Randomized",
                "filter": "ENRLFL='Y'",
                "byvars": "",
                "avar": "",
                "grouptitle": "Analysis Set",
                "grouptitle1": "Enrolled Analysis Set (EAS)",
                "result_style": "n",
                "denom": "&denom",
                "level": 1,
                "newindex": "Y",
                "outds": "unit03"
            },
            {
                "type": "Discrete_simple",
                "comment": "Safety",
                "filter": "SAFFL='Y'",
                "byvars": "",
                "avar": "",
                "grouptitle": "Safety Analysis Set",
                "grouptitle1": "",
                "result_style": "freq_format",
                "denom": "enrlpop",
                "level": 2,
                "newindex": "N",
                "outds": "unit07"
            },
        ]

        return self.generate_program(
            table_id=table_id,
            table_name="Subject Disposition",
            analysis_set="All Screened Subjects",
            group_by="TRT01PN",
            dataset="adsl",
            treatment_labels=treatment_labels,
            analysis_units=analysis_units,
            data_prep_code=self.DATA_PREP_DISPOSITION
        )

    def generate_ae_summary_program(
        self,
        table_id: str = "14.3.1.1",
        treatment_labels: Dict[int, str] = None
    ) -> str:
        """Generate SAS program for Table 14.3.1.1 (AE Summary)."""
        if treatment_labels is None:
            treatment_labels = {1: "Treatment A", 2: "Treatment B", 3: "Treatment C"}

        analysis_units = [
            {
                "type": "Discrete_simple",
                "comment": "Subjects with any TEAE",
                "filter": "TRTEMFL='Y'",
                "byvars": "",
                "avar": "USUBJID",
                "grouptitle": "Subjects with any Treatment-Emergent Adverse Events",
                "grouptitle1": "",
                "result_style": "freq_format",
                "denom": "safpop",
                "level": 1,
                "newindex": "Y",
                "outds": "unit01"
            },
            {
                "type": "Discrete_simple",
                "comment": "Grade 3 or higher",
                "filter": "TRTEMFL='Y' and AETOXGR >= 3",
                "byvars": "",
                "avar": "USUBJID",
                "grouptitle": "Grade 3 or Higher",
                "grouptitle1": "",
                "result_style": "freq_format",
                "denom": "safpop",
                "level": 2,
                "newindex": "N",
                "outds": "unit02"
            },
        ]

        return self.generate_program(
            table_id=table_id,
            table_name="Overall Summary of Treatment-Emergent Adverse Events",
            analysis_set="Safety Analysis Set",
            group_by="TRTPN",
            dataset="adae",
            treatment_labels=treatment_labels,
            analysis_units=analysis_units,
            data_prep_code=self.DATA_PREP_DISPOSITION
        )

    def generate_medical_history_program(
        self,
        table_id: str = "14.1.3.1",
        treatment_labels: Dict[int, str] = None
    ) -> str:
        """Generate SAS program for Table 14.1.3.1 (Medical History)."""
        if treatment_labels is None:
            treatment_labels = {1: "Treatment A", 2: "Treatment B", 3: "Treatment C"}

        data_prep = """
data &inds;
  set &inds;
  DURDIAG=DURDIAG/30.4375;
  output;
  length _metaloc $200;
  do i =1 to countc(METALOC,",")+1;
     _metaloc =strip(scan(scan(METALOC,i,","),1,":"));
     if _metaloc ^in ('ADRENAL GLAND','BONE','BRAIN','LIVER','LUNG','PERICARDIAL EFFUSION','KIDNEY','') then _metaloc='OTHER';
     output;
  end;
run;
"""

        analysis_units = [
            {
                "type": "Descriptive_Basic",
                "comment": "Time from Initial Histological Diagnosis",
                "filter": "",
                "byvars": "",
                "avar": "DURDIAG",
                "grouptitle": "Time from Initial Histological Diagnosis to Study Treatment (Months)",
                "result_style": "n mean sd median min_max",
                "denom": "&denom",
                "level": 1,
                "newindex": "Y",
                "outds": "unit01"
            },
            {
                "type": "Discrete_simple",
                "comment": "Histology",
                "filter": "",
                "byvars": "",
                "avar": "HIST",
                "grouptitle": "Histology",
                "grouptitle1": "",
                "result_style": "freq_format",
                "denom": "&denom",
                "level": 1,
                "newindex": "Y",
                "outds": "unit02"
            },
            {
                "type": "Discrete_simple",
                "comment": "Tumor Stage at study Entry",
                "filter": "",
                "byvars": "",
                "avar": "STAGESE",
                "grouptitle": "Tumor Stage at study Entry",
                "grouptitle1": "",
                "result_style": "freq_format",
                "denom": "&denom",
                "avar_displayformat": "$TUMSTAG.",
                "level": 1,
                "newindex": "Y",
                "outds": "unit03"
            },
        ]

        return self.generate_program(
            table_id=table_id,
            table_name="Medical History and Disease Characteristics",
            analysis_set="Enrolled Analysis Set",
            group_by="TRT01PN",
            dataset="adsl",
            treatment_labels=treatment_labels,
            analysis_units=analysis_units,
            data_prep_code=data_prep
        )

    def save_program(
        self,
        program_code: str,
        output_path: str
    ) -> None:
        """Save generated SAS program to file."""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(program_code)


def generate_sas_program(
    table_id: str,
    analysis_type: str,
    output_path: str = None,
    treatment_labels: Dict[int, str] = None
) -> str:
    """
    Generate a SAS program for a given table.

    Args:
        table_id: Table identifier (e.g., "14.1.1.1")
        analysis_type: Type of analysis
        output_path: Optional path to save the program
        treatment_labels: Dict mapping treatment number to label

    Returns:
        Generated SAS program code
    """
    generator = SASProgramGenerator()

    if analysis_type == "disposition" or table_id == "14.1.1.1":
        program = generator.generate_disposition_program(table_id, treatment_labels)
    elif analysis_type == "ae_summary" or table_id == "14.3.1.1":
        program = generator.generate_ae_summary_program(table_id, treatment_labels)
    elif analysis_type == "medical_history" or table_id == "14.1.3.1":
        program = generator.generate_medical_history_program(table_id, treatment_labels)
    else:
        # Generic program
        program = generator.generate_program(
            table_id=table_id,
            table_name=f"Table {table_id}",
            analysis_set="Analysis Set",
            group_by="TRT01PN",
            dataset="adsl",
            treatment_labels=treatment_labels
        )

    if output_path:
        generator.save_program(program, output_path)

    return program
