/*--------------------------------------------------------------------------------------------*
Company Name:         Generated by AI Agent
Protocol ID:
Program:              Table 14.1.1.1.sas
Purpose:              Generate Subject Disposition
Input Files:          ADaM.ADSL
Output Files:         RTF
Macro:
Author:               AI Agent
Date Generated:       2026-04-20
*--------------------------------------------------------------------------------------------**/

%include '_setup.sas';

%let Columns = %str(rowlabel _col_1 _col_2 _col_3 _col_99999);

%let tableid = %str(Table 14.1.1.1);

%let tablename = %str(Subject Disposition);

%let tablepop = %str(Enrolled Analysis Set);

%let datasource = %str(ADaM.ADSL);

%let column = %str(TRT01PN);

%let denom = %str(ADSL);

%let denomvar = %str(&column);

%let total = %str(Y);

%let g_distinct = %str(USUBJID);

%let byvar_format = %str( );

%let MaxPageLines = %str(21);

%let BreakIndexGroup = %str(N);

%let reflisting = %str(Listing 16.2.1.1);

%let column_definition = %str(
rowlabel label="" width=2.5 headerjust=l columnjust=l
_col_1 label="5.4 mg/kg`(N=&n_1)" width=1 headerjust=c columnjust=c
_col_2 label="6.4 mg/kg`(N=&n_2)" width=1 headerjust=c columnjust=c
_col_3 label="7.4 mg/kg`(N=&n_3)" width=1 headerjust=c columnjust=c
_col_99999 label="Total`(N=&n_99999)" width=1 headerjust=c columnjust=c
);

%import;

data enrlpop;
  set adsl;
  where enrlfl='Y';
 run;

 data safpop;
   set adsl;
   where saffl='Y';
  run;

/*Screened*/
%Discrete_simple(
inds = &inds
,filter = SCRNFL='Y'
,byvars = 
,column = &column
,avar = 
,grouptitle = No. of Subjects Screened
,grouptitle1 = ongoing
,total = &total
,result_style = n
,denom = &denom
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 1
,distinct = &g_distinct
,group_position = TOP
,newindex = Y
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit01
);


/*Screen failed*/
%Discrete_simple(
inds = &inds
,filter = SCNEFL='Y'
,byvars = 
,column = &column
,avar = 
,grouptitle = No. of Subjects Screen Failed
,grouptitle1 = 
,total = &total
,result_style = n
,denom = &denom
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 1
,distinct = &g_distinct
,group_position = TOP
,newindex = N
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit02
);


/*Enrolled/Randomized*/
%Discrete_simple(
inds = &inds
,filter = ENRLFL='Y'
,byvars = 
,column = &column
,avar = 
,grouptitle = Analysis Set
,grouptitle1 = Enrolled Analysis Set (EAS)
,total = &total
,result_style = n
,denom = &denom
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 1
,distinct = &g_distinct
,group_position = TOP
,newindex = Y
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit03
);


/*Safety*/
%Discrete_simple(
inds = &inds
,filter = SAFFL='Y'
,byvars = 
,column = &column
,avar = 
,grouptitle = Safety Analysis Set
,grouptitle1 = 
,total = &total
,result_style = freq_format
,denom = enrlpop
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 2
,distinct = &g_distinct
,group_position = TOP
,newindex = N
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit07
);


/*Response Evaluable Set*/
%Discrete_simple(
inds = &inds
,filter = RESFL='Y'
,byvars = 
,column = &column
,avar = 
,grouptitle = Response Evaluable Set
,grouptitle1 = 
,total = &total
,result_style = freq_format
,denom = enrlpop
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 2
,distinct = &g_distinct
,group_position = TOP
,newindex = N
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit08
);


/*Pharmacokinetic*/
%Discrete_simple(
inds = &inds
,filter = PKFL='Y'
,byvars = 
,column = &column
,avar = 
,grouptitle = PK Analysis Set
,grouptitle1 = 
,total = &total
,result_style = freq_format
,denom = enrlpop
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 2
,distinct = &g_distinct
,group_position = TOP
,newindex = N
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit09
);


/*Ongoing on the Study Treatment*/
%Discrete_simple(
inds = &inds
,filter = ONGFL='Y'
,byvars = 
,column = &column
,avar = 
,grouptitle = Treatment Status in the EAS
,grouptitle1 = Ongoing
,total = &total
,result_style = freq_format
,denom = enrlpop
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 1
,distinct = &g_distinct
,group_position = TOP
,newindex = Y
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit12
);


/*Discontinued from Study Treatment*/
%Discrete_simple(
inds = &inds
,filter = DISCTFL='Y'
,byvars = 
,column = &column
,avar = 
,grouptitle = Discontinued
,grouptitle1 = 
,total = &total
,result_style = freq_format
,denom = enrlpop
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 2
,distinct = &g_distinct
,group_position = TOP
,newindex = N
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit13
);


/*Primary Reason for discontinuation from Study Treatment*/
%Discrete_simple(
inds = &inds
,filter = DISCTFL='Y'
,byvars = DCTREAS
,column = &column
,avar = 
,grouptitle = Primary Reason for Discontinuation from Study Treatment
,grouptitle1 = 
,total = &total
,result_style = freq_format
,denom = safpop
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = $DCTREAS.
,level = 3
,distinct = &g_distinct
,group_position = TOP
,newindex = N
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit14
);


/*Potential Study Follow-up (Days)*/
%Descriptive_Basic(
inds = &inds
,filter = 
,column = &column
,byvars = 
,grouptitle = Duration of Follow-up (months)
,avar = STUDURM
,chgvar = 
,pchgvar = 
,basevar = 
,total = &total
,result_style = n mean sd median min_max
,denom = &denom
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 1
,distinct = &g_distinct
,group_position = TOP
,newindex = Y
,FillBlankColumn = Y
,DelBlankRow = N
,outfilter = 
,layout = VV
,geoinds = 
,alpha = 0.05
,autoformat = &autoformat
,autoformatby = 
,decimalplace = 
,basedecimalplace = 
,compspace = Y
,groupstyle = 
,FillBlankStyle = &misschar
,round = 
,byformat_jointype = full
,chgfilter = col1^=.
,pchgdecimal = 1
,calculateCI = N
,index = 
,totalfilter = 
, outds = unit19
);

data unit01;
 set unit01;
  array col _col_:;
  do over col;
    if vname(col)^='_col_99999' then col='';
  end;
 run;


 data unit02;
 set unit02;
   array col _col_:;
  do over col;
    if vname(col)^='_col_99999' then col='';
  end;
 run;
%output;%delvars;

run;
