/*--------------------------------------------------------------------------------------------*
Company Name:         Generated by AI Agent
Protocol ID:
Program:              Table 14.1.1.2.sas
Purpose:              Generate Table 14.1.1.2
Input Files:          ADaM.ADSL
Output Files:         RTF
Macro:
Author:               AI Agent
Date Generated:       2026-04-20
*--------------------------------------------------------------------------------------------**/

%include '_setup.sas';

%let Columns = %str(rowlabel _col_1 _col_2 _col_3 _col_99999);

%let tableid = %str(Table 14.1.1.2);

%let tablename = %str(Table 14.1.1.2);

%let tablepop = %str(Analysis Set);

%let datasource = %str(ADaM.ADSL);

%let column = %str(TRTPN);

%let denom = %str(ADSL);

%let denomvar = %str(&column);

%let total = %str(Y);

%let g_distinct = %str(USUBJID);

%let byvar_format = %str( );

%let MaxPageLines = %str(21);

%let BreakIndexGroup = %str(N);

%let reflisting = %str(Listing 16.2.1.1);

%let column_definition = %str(
rowlabel label="" width=2.5 headerjust=l columnjust=l
_col_1 label="5.4 mg/kg`(N=&n_1)" width=1 headerjust=c columnjust=c
_col_2 label="6.4 mg/kg`(N=&n_2)" width=1 headerjust=c columnjust=c
_col_3 label="7.4 mg/kg`(N=&n_3)" width=1 headerjust=c columnjust=c
_col_99999 label="Total`(N=&n_99999)" width=1 headerjust=c columnjust=c
);

%import;

data enrlpop;
  set adsl;
  where enrlfl='Y';
 run;

 data safpop;
   set adsl;
   where saffl='Y';
  run;

/*Analysis*/
%Discrete_simple(
inds = &inds
,filter = 1=1
,byvars = 
,column = &column
,avar = 
,grouptitle = Analysis Set
,grouptitle1 = 
,total = &total
,result_style = n
,denom = &denom
,denomvar = &denomvar
,avar_displayformat = 
,byvars_displayformat = 
,level = 1
,distinct = &g_distinct
,group_position = TOP
,newindex = Y
,weightvar = 
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = 
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = 
,CalculateCI = N
,keepdenom = Y
,distinct_event = 
,byformat_jointype = full
,sortByCol = 
,avarselcrit = 
,total_style = 
,totalfilter = 
,index = 
,CalculateP = 
,compspace = Y
,alpha = 0.05
, outds = unit01
);

data unit01;
 set unit01;
  array col _col_:;
  do over col;
    if vname(col)^='_col_99999' then col='';
  end;
 run;


 data unit02;
 set unit02;
   array col _col_:;
  do over col;
    if vname(col)^='_col_99999' then col='';
  end;
 run;
%output;%delvars;

run;
