"""add_subscription_fields

Revision ID: 944feaaba3eb
Revises: 0001
Create Date: 2026-06-24 15:40:57.898870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944feaaba3eb'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan_type', sa.String(length=50), nullable=True, server_default='free'))
    op.add_column('tenants', sa.Column('lemon_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('subscription_status', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('monthly_usage_count', sa.Integer(), nullable=True, server_default='0'))
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('users', sa.Column('plan_type', sa.String(length=50), nullable=True, server_default='free'))
    op.add_column('users', sa.Column('lemon_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('monthly_usage_count', sa.Integer(), nullable=True, server_default='0'))
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_column('users', 'monthly_usage_count')
    op.drop_column('users', 'current_period_end')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'lemon_subscription_id')
    op.drop_column('users', 'plan_type')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'monthly_usage_count')
    op.drop_column('tenants', 'current_period_end')
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'lemon_subscription_id')
    op.drop_column('tenants', 'plan_type')
    # ### end Alembic commands ###
