"""
Code Generator Agent - Generates SAS programs from macro selections.
Matches the exact format of .knowledge/TLF/Pgm/Table XX.X.X.X.sas files.
"""

from typing import Optional


class CodeGeneratorAgent:
    """Agent for generating SAS TLF programs matching reference format."""

    # Header template matching reference TLF programs exactly
    HEADER_TEMPLATE = """/*--------------------------------------------------------------------------------------------*
Company Name:         Generated by AI Agent
Protocol ID:
Program:              Table {table_id}.sas
Purpose:              Generate {table_name}
Input Files:          ADaM.{dataset_upper}
Output Files:         RTF
Macro:
Author:               AI Agent
Date Generated:       {timestamp}
*--------------------------------------------------------------------------------------------**/

%include '_setup.sas';

%let Columns = %str(rowlabel _col_1 _col_2 _col_3 _col_99999);

%let tableid = %str(Table {table_id});

%let tablename = %str({table_name});

%let tablepop = %str({analysis_set});

%let datasource = %str(ADaM.{dataset_upper});

%let column = %str({group_by});

%let denom = %str({dataset_upper});

%let denomvar = %str(&column);

%let total = %str(Y);

%let g_distinct = %str(USUBJID);

%let byvar_format = %str( );

%let MaxPageLines = %str(21);

%let BreakIndexGroup = %str(N);

%let reflisting = %str(Listing 16.2.1.1);

%let column_definition = %str(
rowlabel label="" width=2.5 headerjust=l columnjust=l
_col_1 label="5.4 mg/kg`(N=&n_1)" width=1 headerjust=c columnjust=c
_col_2 label="6.4 mg/kg`(N=&n_2)" width=1 headerjust=c columnjust=c
_col_3 label="7.4 mg/kg`(N=&n_3)" width=1 headerjust=c columnjust=c
_col_99999 label="Total`(N=&n_99999)" width=1 headerjust=c columnjust=c
);

%import;

{data_prep}
"""

    DATA_PREP_TEMPLATE = """
data enrlpop;
  set adsl;
  where enrlfl='Y';
 run;

 data safpop;
   set adsl;
   where saffl='Y';
  run;
"""

    # Discrete_simple analysis unit - EXACT match to reference format
    DISCRETE_SIMPLE_UNIT = """
/*{comment}*/
%Discrete_simple(
inds = &inds
,filter = {filter}
,byvars = {byvars}
,column = &column
,avar = {avar}
,grouptitle = {grouptitle}
,grouptitle1 = {grouptitle1}
,total = &total
,result_style = {result_style}
,denom = {denom}
,denomvar = &denomvar
,avar_displayformat = {avar_displayformat}
,byvars_displayformat = {byvars_displayformat}
,level = {level}
,distinct = &g_distinct
,group_position = TOP
,newindex = {newindex}
,weightvar = {weightvar}
,FillBlankColumn = Y
,DelBlankRow = N
,layout = V
,outfilter = {outfilter}
,FillBlankStyle = &FillBlankStyle
,NoFilterforNOE = Y
,groupstyle = {groupstyle}
,CalculateCI = N
,keepdenom = Y
,distinct_event = {distinct_event}
,byformat_jointype = full
,sortByCol = {sortBycol}
,avarselcrit = {avarselcrit}
,total_style = {total_style}
,totalfilter = {totalfilter}
,index = {index}
,CalculateP = {CalculateP}
,compspace = Y
,alpha = 0.05
, outds = {outds}
);
"""

    # Descriptive_Basic analysis unit - for continuous variables
    DESCRIPTIVE_BASIC_UNIT = """
/*{comment}*/
%Descriptive_Basic(
inds = &inds
,filter = {filter}
,column = &column
,byvars = {byvars}
,grouptitle = {grouptitle}
,avar = {avar}
,chgvar = {chgvar}
,pchgvar = {pchgvar}
,basevar = {basevar}
,total = &total
,result_style = {result_style}
,denom = {denom}
,denomvar = &denomvar
,avar_displayformat = {avar_displayformat}
,byvars_displayformat = {byvars_displayformat}
,level = {level}
,distinct = &g_distinct
,group_position = TOP
,newindex = {newindex}
,FillBlankColumn = Y
,DelBlankRow = N
,outfilter = {outfilter}
,layout = VV
,geoinds = {geoinds}
,alpha = 0.05
,autoformat = &autoformat
,autoformatby = {autoformatby}
,decimalplace = {decimalplace}
,basedecimalplace = {basedecimalplace}
,compspace = Y
,groupstyle = {groupstyle}
,FillBlankStyle = &misschar
,round = {round}
,byformat_jointype = full
,chgfilter = col1^=.
,pchgdecimal = 1
,calculateCI = N
,index = {index}
,totalfilter = {totalfilter}
, outds = {outds}
);
"""

    # Footer template
    FOOTER_TEMPLATE = """
data {unit_prefix}01;
 set {unit_prefix}01;
  array col _col_:;
  do over col;
    if vname(col)^='_col_99999' then col='';
  end;
 run;


 data {unit_prefix}02;
 set {unit_prefix}02;
   array col _col_:;
  do over col;
    if vname(col)^='_col_99999' then col='';
  end;
 run;
%output;%delvars;

run;
"""

    # Table 14.1.1.1 specific analysis units - copied from reference
    TABLE_14111_UNITS = [
        {
            "type": "Discrete_simple",
            "comment": "Screened",
            "filter": "SCRNFL='Y'",
            "byvars": "",
            "avar": "",
            "grouptitle": "No. of Subjects Screened",
            "grouptitle1": "ongoing",
            "result_style": "n",
            "denom": "&denom",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 1,
            "newindex": "Y",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit01"
        },
        {
            "type": "Discrete_simple",
            "comment": "Screen failed",
            "filter": "SCNEFL='Y'",
            "byvars": "",
            "avar": "",
            "grouptitle": "No. of Subjects Screen Failed",
            "grouptitle1": "",
            "result_style": "n",
            "denom": "&denom",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 1,
            "newindex": "N",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit02"
        },
        {
            "type": "Discrete_simple",
            "comment": "Enrolled/Randomized",
            "filter": "ENRLFL='Y'",
            "byvars": "",
            "avar": "",
            "grouptitle": "Analysis Set",
            "grouptitle1": "Enrolled Analysis Set (EAS)",
            "result_style": "n",
            "denom": "&denom",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 1,
            "newindex": "Y",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit03"
        },
        {
            "type": "Discrete_simple",
            "comment": "Safety",
            "filter": "SAFFL='Y'",
            "byvars": "",
            "avar": "",
            "grouptitle": "Safety Analysis Set",
            "grouptitle1": "",
            "result_style": "freq_format",
            "denom": "enrlpop",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 2,
            "newindex": "N",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit07"
        },
        {
            "type": "Discrete_simple",
            "comment": "Response Evaluable Set",
            "filter": "RESFL='Y'",
            "byvars": "",
            "avar": "",
            "grouptitle": "Response Evaluable Set",
            "grouptitle1": "",
            "result_style": "freq_format",
            "denom": "enrlpop",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 2,
            "newindex": "N",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit08"
        },
        {
            "type": "Discrete_simple",
            "comment": "Pharmacokinetic",
            "filter": "PKFL='Y'",
            "byvars": "",
            "avar": "",
            "grouptitle": "PK Analysis Set",
            "grouptitle1": "",
            "result_style": "freq_format",
            "denom": "enrlpop",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 2,
            "newindex": "N",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit09"
        },
        {
            "type": "Discrete_simple",
            "comment": "Ongoing on the Study Treatment",
            "filter": "ONGFL='Y'",
            "byvars": "",
            "avar": "",
            "grouptitle": "Treatment Status in the EAS",
            "grouptitle1": "Ongoing",
            "result_style": "freq_format",
            "denom": "enrlpop",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 1,
            "newindex": "Y",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit12"
        },
        {
            "type": "Discrete_simple",
            "comment": "Discontinued from Study Treatment",
            "filter": "DISCTFL='Y'",
            "byvars": "",
            "avar": "",
            "grouptitle": "Discontinued",
            "grouptitle1": "",
            "result_style": "freq_format",
            "denom": "enrlpop",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 2,
            "newindex": "N",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit13"
        },
        {
            "type": "Discrete_simple",
            "comment": "Primary Reason for discontinuation from Study Treatment",
            "filter": "DISCTFL='Y'",
            "byvars": "DCTREAS",
            "avar": "",
            "grouptitle": "Primary Reason for Discontinuation from Study Treatment",
            "grouptitle1": "",
            "result_style": "freq_format",
            "denom": "safpop",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "$DCTREAS.",
            "level": 3,
            "newindex": "N",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "distinct_event": "",
            "sortBycol": "",
            "avarselcrit": "",
            "total_style": "",
            "totalfilter": "",
            "index": "",
            "CalculateP": "",
            "outds": "unit14"
        },
        {
            "type": "Descriptive_Basic",
            "comment": "Potential Study Follow-up (Days)",
            "filter": "",
            "byvars": "",
            "avar": "STUDURM",
            "chgvar": "",
            "pchgvar": "",
            "basevar": "",
            "grouptitle": "Duration of Follow-up (months)",
            "grouptitle1": "",
            "result_style": "n mean sd median min_max",
            "denom": "&denom",
            "denomvar": "&denomvar",
            "avar_displayformat": "",
            "byvars_displayformat": "",
            "level": 1,
            "newindex": "Y",
            "weightvar": "",
            "outfilter": "",
            "groupstyle": "",
            "geoinds": "",
            "autoformatby": "",
            "decimalplace": "",
            "basedecimalplace": "",
            "round": "",
            "index": "",
            "totalfilter": "",
            "outds": "unit19"
        },
    ]

    def __init__(self, rag_retriever=None):
        self.rag = rag_retriever

    def generate_program(
        self,
        table_id: str,
        table_name: str,
        analysis_set: str,
        group_by: str,
        dataset: str,
        macro_calls: list[dict] = None,
        population_filter: str = "1=1"
    ) -> str:
        """
        Generate a complete SAS TLF program matching reference format.

        Args:
            table_id: Table identifier (e.g., "14.1.1.1")
            table_name: Table name
            analysis_set: Analysis set name
            group_by: Grouping variable (usually treatment)
            dataset: ADaM dataset name
            macro_calls: List of macro call specifications (optional)
            population_filter: Population filter condition

        Returns:
            Generated SAS program code
        """
        from datetime import datetime

        dataset_upper = dataset.upper()

        # Build header
        header = self.HEADER_TEMPLATE.format(
            table_id=table_id,
            table_name=table_name,
            analysis_set=analysis_set,
            group_by=group_by,
            dataset_upper=dataset_upper,
            timestamp=datetime.now().strftime("%Y-%m-%d"),
            data_prep=self.DATA_PREP_TEMPLATE.strip()
        )

        # Generate analysis units based on table_id
        if table_id == "14.1.1.1":
            analysis_units = self._generate_14111_units()
        else:
            # Default units for other tables
            analysis_units = self._generate_default_units(dataset_upper, group_by)

        # Build footer
        footer = self.FOOTER_TEMPLATE.format(unit_prefix="unit")

        # Combine
        full_code = header + "\n".join(analysis_units) + footer
        return full_code

    def _generate_14111_units(self) -> list[str]:
        """Generate analysis units for Table 14.1.1.1 - matches reference exactly."""
        units = []
        for unit_def in self.TABLE_14111_UNITS:
            if unit_def["type"] == "Discrete_simple":
                unit_code = self.DISCRETE_SIMPLE_UNIT.format(**unit_def)
            elif unit_def["type"] == "Descriptive_Basic":
                unit_code = self.DESCRIPTIVE_BASIC_UNIT.format(**unit_def)
            else:
                continue
            units.append(unit_code)
        return units

    def _generate_default_units(self, dataset_upper: str, group_by: str) -> list[str]:
        """Generate default analysis units for tables without specific config."""
        return [
            self.DISCRETE_SIMPLE_UNIT.format(
                comment="Analysis",
                filter="1=1",
                byvars="",
                avar="",
                grouptitle="Analysis Set",
                grouptitle1="",
                result_style="n",
                denom="&denom",
                denomvar="&denomvar",
                avar_displayformat="",
                byvars_displayformat="",
                level=1,
                newindex="Y",
                weightvar="",
                outfilter="",
                groupstyle="",
                distinct_event="",
                sortBycol="",
                avarselcrit="",
                total_style="",
                totalfilter="",
                index="",
                CalculateP="",
                outds="unit01"
            )
        ]

    def generate_disposition_table(self, dataset: str = "adsl") -> str:
        """Generate Table 14.1.1.1 - Subject Disposition."""
        return self.generate_program(
            table_id="14.1.1.1",
            table_name="Subject Disposition",
            analysis_set="All Screened Subjects",
            group_by="TRT01PN",
            dataset=dataset,
            macro_calls=[]
        )

    def generate_demographics_table(self, dataset: str = "adsl") -> str:
        """Generate Table 14.1.2.1 - Demographics."""
        return self.generate_program(
            table_id="14.1.2.1",
            table_name="Demographic and Baseline Characteristics",
            analysis_set="Enrolled Analysis Set",
            group_by="TRT01PN",
            dataset=dataset,
            macro_calls=[]
        )

    def generate_ae_summary_table(self, dataset: str = "adae") -> str:
        """Generate Table 14.3.1.1 - AE Summary."""
        return self.generate_program(
            table_id="14.3.1.1",
            table_name="Overall Summary of TEAE",
            analysis_set="Safety Analysis Set",
            group_by="TRTPN",
            dataset=dataset,
            macro_calls=[]
        )

    def validate_syntax(self, code: str) -> dict:
        """Validate SAS code syntax."""
        errors = []
        warnings = []

        # Check balanced quotes
        single_quotes = code.count("'")
        if single_quotes % 2 != 0:
            errors.append("Unbalanced single quotes")

        # Check balanced parentheses
        paren_count = 0
        for char in code:
            if char == '(':
                paren_count += 1
            elif char == ')':
                paren_count -= 1
            if paren_count < 0:
                errors.append("Unexpected closing parenthesis")
                break

        if paren_count != 0:
            errors.append("Unbalanced parentheses")

        # Check for required elements
        if "%include" not in code:
            warnings.append("Missing %include statement")

        if "%import" not in code:
            warnings.append("Missing %import statement")

        if "%output" not in code:
            warnings.append("Missing %output statement")

        if "%Discrete_simple" not in code:
            warnings.append("Missing %Discrete_simple macro call")

        return {
            "valid": len(errors) == 0,
            "errors": errors,
            "warnings": warnings
        }
